runtime: python39  # Puedes seleccionar la versión de Python que necesites.
entrypoint: gunicorn -b :$PORT app:app  # app:app debe apuntar a tu aplicación Flask.

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

